skillMetadata:
  sections:
    - name: Wake on Lan
      fields:
        - name: username
          type: text
          label: Username for the Webpage
          value:
        - name: password
          type: password
          label: Password for the Webpage
          value:
        - name: url
          type: text
          label: URL
          value: 
